services:
  database:
    container_name: trashcan-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - db:/data/postgres
    restart: unless-stopped
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    networks:
      - backend
  backend:
    container_name: trashcan-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgres://${PG_USER}:${PG_PASSWORD}@database/${PG_DB}"
      SENDER_EMAIL: ${SENDER_EMAIL}
      PUBLIC_CORS_DOMAIN: https://trashcan-client.${HOST_NAME}
      SENDER_PASSWORD: ${SENDER_PASSWORD}
      RECEIVER_EMAIL: ${RECEIVER_EMAIL}
    image: akagiyuu/smart-trash-bin-backend
    networks:
      - backend
  frontend:
    container_name: trashcan-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - VITE_API_URL=https://trashcan-api.${HOST_NAME}
        - VITE_WS_URL=wss://trashcan-api.${HOST_NAME}
    ports:
      - 5173:80
    image: akagiyuu/smart-trash-bin-frontend
    networks:
      - backend

networks:
  backend:
    name: "trashcan_application_networks"

volumes:
  db:
    name: "trashcan-database"
