on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build frontend
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
        
      - name: DockerHub Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build Image And Push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          build-args: |
            VITE_API_URL=https://trashcan-api.${{ secrets.HOST_NAME }}
            VITE_WS_URL=wss://trashcan-api.${{ secrets.HOST_NAME }}
          push: true
          tags: akagiyuu/smart-trash-bin-frontend:latest

  build-backend:
    name: Build backend
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
        
      - name: DockerHub Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build Image And Push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: akagiyuu/smart-trash-bin-backend:latest
  
  deploy:
    name: Deploy
    runs-on: smart-trashcan
    needs: [build-frontend, build-backend]
    steps:
    - name: Checkout Develop
      uses: actions/checkout@v3

    - name: DockerHub Login
      run: echo ${{ secrets.F_CODE_DOCKER_PASS }} | docker login -u ${{ secrets.F_CODE_DOCKER_USER }} --password-stdin

    - name: Clean Container, Image And Prepare For Deploy
      run: docker compose down --rmi all -v

    - name: Deploy Socket
      run: docker compose --env-file=.env up -d
